# Generated by Django 6.0.5 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='language',
            field=models.CharField(default='Python', max_length=50),
            preserve_default=False,
        ),
    ]
