# Generated by Django 6.0.5 on 2026-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_aiquery_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
